### PR TITLE
Add local oniguruma submodule

### LINKED ISSUE #1059: Cross-compile via Travis-CI too
It seems it's possible to cross-compile in Travis-CI builds.

A few links:

 - http://stackoverflow.com/questions/28155308/how-to-cross-compile-with-mingw-on-linux-for-windows

   This one has a great answer.  We need grab the Mingw pkgs [from a third-party repo](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-from-a-custom-apt-repository) (which I guess we can trust as far as CI goes), then use them in the Travis build.  Ideally Travis would just provide these...

 - https://trac.osgeo.org/geos/ticket/659
 - http://www.scriptscoop.net/t/d39c9eac38a2/how-to-cross-compile-with-mingw-on-linux-for-windows.html
 - http://sourceforge.net/p/mingw-w64/mailman/message/31846195/

### PR DESCRIPTION
**Pull request by erikbrinkman**
This is a test to add oniguruma locally as a submodule. This should allow:

- Control over the oniguruma version
- Regex support in all builds
- The potential to cross compile for windows from TravisCI and move away from appveyor

fixes #1059

### CODE REVIEW

**Comment by erikbrinkman** [comment]
@nicowilliams Here's a branch where oniguruma is configured locally as a submodule. Notes:

- The purpose was to get cross compiling working in travis, so that still needs to be done
- The documentation for compiling should be updated to mention that you need to do `git submodule update --init` before running `autoreconf`, and you might need to add the `-f` flag to autoreconf because of timestamps.
- The autoconf script for oniguruma has a check that automake is at least 1.14, but travis ci is still running precise and so only has automake 1.11. However, I added a line to the `.travis.yml` that just replaces the requirement of 1.14 to 1.11, and the build and all tests succeed, so I think it's just an overspecification. That being said, this workaround is very hacky and may break if the version of oniguruma is ever updated.

**Comment by nicowilliams** [comment]
@erikbrinkman Should we specify a tag for the Oniguruma module?  That would be submodule best practice, no?

**Comment by nicowilliams** [comment]
Anyways, this is great, thanks!

**Comment by erikbrinkman** [comment]
What do you mean a tag for the submodule? The commit it's pegged at is the 6.1.3 tag, but I think only recent versions of git support tags and branches in submodules, so this might be more backwards compatible. Perhaps you mean something different for a tag?

Also, I forgot to mention it, but the Makefile currently refers to the built "libonig.a" that the build produces, instead of whatever library will be built on windows.

**Comment by nicowilliams** [comment]
Oh, hmm, and will we now be including Oniguruma in source tarballs?  I guess... we could, but if not then we need to have `--with-oniguruma` in ./configure for building outside git.

**Comment by erikbrinkman** [comment]
That's a good point. Pro's of including it in tarbars is control over the version, but it would bloat the tarball for people who already have the library. Should I just reintroduce the flag, but have autoconf look to see if the `modules/oniguruma` directory exists and if so, count it as there and put guards around the automake etc?

**Comment by nicowilliams** [comment]
Yes, basically reintroduce `AC_ARG_WITH([oniguruma], ...` in `configure.ac` and have an `AS_IF` handle the case where it's "no" or unset.

**Comment by wtlangford** [comment]
I made these changes and did some other work to better handle precious variables like `CFLAGS` and `LDFLAGS`.

`./configure` will use the system oniguruma, if found, or else default to the submodule.
`./configure --with-oniguruma` is identical to `./configure`
`./configure --with-oniguruma=/p/a/t/h` will add `/p/a/t/h` to the include and library search paths before searching for oniguruma.  If it finds oniguruma, it uses that oniguruma, else defaults to the submodule.
`./configure --without-oniguruma` and `./configure --with-oniguruma=no` will build jq without oniguruma functionality.

**Comment by nicowilliams** [comment]
@wtlangford Yes!!  Thanks!

Go ahead and push it.  I like it.  I can then see to it that it works on Appveyor.

BTW, I wonder if we shouldn't have a better way of handling unsupported features (e.g., math functions not provided by `-lm`).  Maybe we should have a way of defining a function which will trigger a link-time error with a suitable message rather than deferring the error until run-time.  (The reason we don't leave them undefined is that we want the user to know why they're not available.)

**Comment by nicowilliams** [comment]
@wtlangford Do rebase and squash first though.

**Comment by nicowilliams** [comment]
(I didn't know what one could push to the submitter's PR.)

**Comment by wtlangford** [comment]
It's a new feature on github. The default is enabled, but you can opt to
turn it off

**Comment by nicowilliams** [comment]
Thanks!

**Comment by erikbrinkman** [comment]
@wtlangford Thanks for finishing this!

**Comment by nicowilliams** [comment]
Oh, @wtlangford: this actually broke the Travis-CI tests...  I'll look tonight.

**Comment by nicowilliams** [comment]
I've pushed

e7caf68 Attempt to use builtin Oniguruma for CIs
c6374b6 Allow ./configure --with-oniguruma=builtin

to try to get Travis-CI building jq again.

**Comment by svnpenn** [comment]
This commit breaks the Windows build for me, both with "git clone" and "git clone --recursive"

**Comment by wtlangford** [comment]
What's broken in it for you?

**Comment by svnpenn** [comment]
Here it is with "git clone":

~~~
[...]
checking oniguruma.h usability... no
checking oniguruma.h presence... no
checking for oniguruma.h... no
configure: Oniguruma was not found. Will use the packaged oniguruma.
[...]
=== configuring in modules/oniguruma (/var/cache/glade/jq/modules/oniguruma)
configure: WARNING: no configuration information is in modules/oniguruma
[...]
Making all in modules/oniguruma
make[3]: Entering directory '/var/cache/glade/jq/modules/oniguruma'
make[3]: *** No rule to make target 'all'.  Stop.
~~~

Here it is with "git clone --recursive":

~~~
[...]
Submodule 'modules/oniguruma' (https://github.com/kkos/oniguruma.git) registered for path 'modules/oniguruma'
Cloning into '/var/cache/glade/jq/modules/oniguruma'...
Submodule path 'modules/oniguruma': checked out '4ab96b4e2d4614494ca556496dc7d6123a832bea'
[...]
checking oniguruma.h usability... no
checking oniguruma.h presence... no
checking for oniguruma.h... no
configure: Oniguruma was not found. Will use the packaged oniguruma.
[...]
=== configuring in modules/oniguruma (/var/cache/glade/jq/modules/oniguruma)
[...]
config.status: creating onig-config
[...]
Making all in modules/oniguruma
make[3]: Entering directory '/var/cache/glade/jq/modules/oniguruma'
Making all in src
make[4]: Entering directory '/var/cache/glade/jq/modules/oniguruma/src'
make  all-am
make[5]: Entering directory '/var/cache/glade/jq/modules/oniguruma/src'
[...]
make[5]: Leaving directory '/var/cache/glade/jq/modules/oniguruma/src'
[...]
  CC       src/jq_test.lo
In file included from /usr/x86_64-w64-mingw32/sys-root/mingw/include/_mingw.h:12:0,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/crtdefs.h:10,
                 from /usr/x86_64-w64-mingw32/sys-root/mingw/include/assert.h:15,
                 from src/compile.c:4:
src/compile.c:1002:21: error: conflicting types for ‘__imp__environ’
 extern const char **environ;
                     ^
/usr/x86_64-w64-mingw32/sys-root/mingw/include/stdlib.h:208:19: note: previous declaration of ‘__imp__environ’ was here
   extern char *** __MINGW_IMP_SYMBOL(_environ);
                   ^
make[3]: *** [Makefile:1016: src/compile.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
src/builtin.c: In function ‘f_env’:
src/builtin.c:1023:25: warning: initialization from incompatible pointer type [-Wincompatible-pointer-types]
   for (const char **e = environ; *e != NULL; e++) {
                         ^
~~~

**Comment by nicowilliams** [comment]
The problem is the environ thing.  I'll fix it.

**Comment by wtlangford** [comment]
Yep, this was actually broken by https://github.com/stedolan/jq/pull/1353.  I was already looking into it. 😄 

That said, it looks like mingw gives you an `extern char *** __MINGW_IMP_SYMBOL(_environ)`, while POSIX promises an `extern char ** environ`.

This may be unpleasant...

**Comment by nicowilliams** [comment]
Hmm?

```
./mingw/mingw-w64-x86_64/x86_64-w64-mingw32/include/tchar.h:#define _tenviron environ
./mingw/mingw-w64-x86_64/x86_64-w64-mingw32/include/stdlib.h:  extern char **environ;
./mingw/mingw-w64-x86_64/x86_64-w64-mingw32/include/stdlib.h:#define environ _environ
```

**Comment by nicowilliams** [comment]
@svnpenn Yes, now you have to git submodule init --update --recursive or whatever.

**Comment by svnpenn** [comment]
@nicowilliams thanks for that, but it appears that even if you fix "the environ
thing", we still have a problem. If:

- No system-installed Oniguruma
- No special prefix Oniguruma
- No vendored oniguruma module

Shouldn’t JQ fall back to `--without-oniguruma` or similar. My first example
seems to illustrate that it does not.

**Comment by wtlangford** [comment]
Strange.  @svnpenn's log output had 
```
src/compile.c:1002:21: error: conflicting types for ‘__imp__environ’
 extern const char **environ;
                     ^
/usr/x86_64-w64-mingw32/sys-root/mingw/include/stdlib.h:208:19: note: previous declaration of ‘__imp__environ’ was here
   extern char *** __MINGW_IMP_SYMBOL(_environ);
                   ^
```
...Oh, and now I see that that's _environ.  I bet that's some mingw hackery.

Anyways, yeah, we should probably fall back to "no oniguruma" in the case where there's no oniguruma around and the vendored module hasn't been cloned.

**Comment by nicowilliams** [comment]
@svnpenn: the idea with having Oniguruma as a git submodule is that we now never need to build with `--without-oniguruma` -- you always have a copy.

I still need to make sure `make dist` works though.  I.e., a copy of Oniguruma needs to be included in the `make dist` tarball too.

**Comment by nicowilliams** [comment]
@wtlangford Sure, we could do that.  It's probably very simple.

**Comment by wtlangford** [comment]
I'd rather `make` not fail strangely because you didn't do the submodule thing.

I'll make it noisy in the configure logs that oniguruma is disabled in this state.

**Comment by nicowilliams** [comment]
sure, let me see if I can whip that up.

**Comment by svnpenn** [comment]
@nicowilliams the current build [violates POLA][x]. If JQ can run without 
Oniguruma (it can), then the sane thing to do it build without Oniguruma when
it cannot be found, and to issue a warning.

[x]://wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by nicowilliams** [comment]
@svnpenn Thanks for the bug report.  I've pushed a fix to `master`.

**Comment by svnpenn** [comment]
@nicowilliams both are still broken? "git clone":

~~~
[...]
checking oniguruma.h usability... no
checking oniguruma.h presence... no
checking for oniguruma.h... no
configure: Oniguruma was not found. Will use the packaged oniguruma.
[...]
Making all in modules/oniguruma
make[3]: Entering directory '/var/cache/glade/jq/modules/oniguruma'
make[3]: *** No rule to make target 'all'.  Stop.
~~~

"git clone --recursive":

~~~
[...]
Submodule 'modules/oniguruma' (https://github.com/kkos/oniguruma.git) registered for path 'modules/oniguruma'
Cloning into '/var/cache/glade/jq/modules/oniguruma'...
Submodule path 'modules/oniguruma': checked out '4ab96b4e2d4614494ca556496dc7d6123a832bea'
[...]
checking oniguruma.h usability... no
checking oniguruma.h presence... no
checking for oniguruma.h... no
configure: Oniguruma was not found. Will use the packaged oniguruma.
[...]
=== configuring in modules/oniguruma (/var/cache/glade/jq/modules/oniguruma)
[...]
config.status: creating onig-config
[...]
Making all in modules/oniguruma
make[3]: Entering directory '/var/cache/glade/jq/modules/oniguruma'
Making all in src
make[4]: Entering directory '/var/cache/glade/jq/modules/oniguruma/src'
make  all-am
make[5]: Entering directory '/var/cache/glade/jq/modules/oniguruma/src'
[...]
  CC       src/main.o
In file included from src/parser.y:124:0:
src/lexer.h:44:19: error: conflicting types for ‘jq_yylex’
src/parser.y:149:5: note: in expansion of macro ‘yylex’
 int yylex(YYSTYPE* yylval, YYLTYPE* yylloc, block* answer, int* errors,
     ^
In file included from src/parser.y:124:0:
src/lexer.h:405:12: note: previous declaration of ‘jq_yylex’ was here
src/parser.y: In function ‘jq_yylex’:
src/parser.y:152:13: error: too few arguments to function ‘jq_yylex’
   int tok = jq_yylex(yylval, yylloc, lexer);
             ^
In file included from src/parser.y:124:0:
src/lexer.h:44:19: note: declared here
src/parser.y:149:5: note: in expansion of macro ‘yylex’
 int yylex(YYSTYPE* yylval, YYLTYPE* yylloc, block* answer, int* errors,
     ^
make[3]: *** [Makefile:1016: src/parser.lo] Error 1

~~~

**Comment by nicowilliams** [comment]
@svnpenn I've no idea what the yylex issue is about; I cannot reproduce it.  What are you building on?  What is the HEAD commit of master that you're building?

**Comment by svnpenn** [comment]
@nicowilliams I am using Cygwin, which I have been using for almost 4 years
without a problem:

http://github.com/svnpenn/a/commit/017c646

Here is my current build script:

http://github.com/svnpenn/glade/tree/master/jq

and current HEAD:

~~~
$ git log -1
commit 63791b795a984e977e6a45471731a28af252097e
Author: William Langford <wlangfor@gmail.com>
Date:   Sun Feb 26 19:50:10 2017 -0500

    Fix name of builtins in the builtins/0 output
~~~

**Comment by nicowilliams** [comment]
@svnpenn You can't just clone, cd, make.  You have to autoreconf -fi and ./configure before you can make.

**Comment by nicowilliams** [comment]
@svnpenn Also, in a script you should probably do this:

```
git clone https://github.com/stedolan/jq jq && cd jq && autoreconf -fi && ./configure && make
```

Or otherwise `set -e` or equivalent.  Perhaps you had a jq directory lying around that was configured and the git clone failed?

**Comment by svnpenn** [comment]
@nicowilliams I think you mixed up my links. My first link is from 4 years ago. 2nd link is my current one

**Comment by nicowilliams** [comment]
@svnpenn Dunno what to tell you.  The yylex thing doesn't happen on any of Linux, OS X, or Windows.  At some point I'll make ./configure w/o Oniguruma installed and without submodules checked out, work.  In the meantime you have an option: --with-oniguruma=no.
