### ISSUE TITLE
master build failure on OS X 10.8:  jv_alloc.c:14: error: thread-local storage not supported for this target

### ISSUE THREAD

**Issue by minaguib** [stedolan/jq#340]
master (currently at 917334d18ab0a5e6dc3c3d8af1bb8edb3623ca0d) fails to build on OS X 10.8:

```
$ make clean all
 rm -f jq
test -z "libjq.la" || rm -f libjq.la
rm -f ./so_locations
rm -rf .libs _libs
rm -f version.h .remake-version-h
rm -f *.o
test -z "tests/all.log" || rm -f tests/all.log
test -z "tests/all.trs" || rm -f tests/all.trs
test -z "test-suite.log" || rm -f test-suite.log
rm -f *.lo
  GEN      version.h
make  all-am
  CC       locfile.lo
  CC       bytecode.lo
  CC       compile.lo
  CC       execute.lo
  CC       builtin.lo
  CC       jv.lo
  CC       jv_parse.lo
  CC       jv_print.lo
  CC       jv_dtoa.lo
  CC       jv_unicode.lo
  CC       jv_aux.lo
  CC       jv_file.lo
  CC       jv_alloc.lo
jv_alloc.c:14: error: thread-local storage not supported for this target
make[1]: *** [jv_alloc.lo] Error 1
make: *** [all] Error 2
```
