### ISSUE TITLE
sort() example in the manual doesn't compile on jqplay.org

### ISSUE THREAD

**Issue by deweerdt** [stedolan/jq#703]
Hi,

The second example on the manual:
jq 'sort(.foo)'

Results in the following error message if you click on 'Run':
error: too many arguments to sort (expected 0 but got 1)
sort(.foo)1 compile error

Frederik

**Comment by pkoppstein** [comment]
@deweerdt - Unfortunately the manual is out-of-sync with jqplay and jq 1.4.  On jqplay, to sort by a key, "a", you could use sort_by(.a).  Please note that this will also work in the upcoming jq 1.5.

**Comment by dtolnay** [comment]
Quoting from #860:

> There has been some back-and-forth regarding sort/1, which unfortunately has made it somewhat difficult to match different versions of jq with different versions of the documentation.

> For your reference, the documentation at "master" currently documents sort/0 and sort_by/1; these have not changed and there is no plan to change their specification.

> The plan is for sort/1 to sort the input array by the specified comparator.

The manual no longer has the example with sort(.foo).
